# 应用服务 WEB 访问端口
server:
  port: 8081

spring:
  profiles:
    #默认是开发模式
    active: dev
#  jackson:
#    # 设置后台反参若字段值为null，则不返回
#    default-property-inclusion: non_null
#    # 设置日期字段格式
#    date-format: yyyy-MM-dd HH:mm:ss