# 应用服务 WEB 访问端口
server:
  port: 8081

spring:
  profiles:
    #默认是开发模式
    active: dev
jwt:
  # 签发人
  issuer: liyuwang
  # 秘钥
  secret: AcO1orRHKz7kwweftC5HxWUtu5pnHv9VMyQq9k1VIvlvea81ybAljx3uaEtTv4i0xhAqyzAS+t7SNdJdyvgUZw==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer


